base_dir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('driver/', include('driver.urls')),
    path('vehicle/', include('vehicle.urls')),
    path('parking_space/', include('parking_space.urls')),
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
    path('', include('core.urls')),    
    path('admin_panel/', admin.site.urls),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('pre_finish/<int:parking_space_id>', views.pre_finish, name='pre_finish'),
    path('finish/<int:parking_space_id>/<int:vehicle_id>', views.finish, name='finish'),
    path('', views.index, name='index'),
]

vehicle/urls.py
from django.urls import path
from vehicle import views

app_name = 'vehicle'

urlpatterns = [
    path('vehicle_register_form', views.VehicleRegisterFormView.as_view(), name='vehicle_register_form'),

    path('saving_vehicle', views.saving_vehicle, name='saving_vehicle'),

    path('registered_vehicle', views.registered_vehicle, name='registered_vehicle'),

    path('delete_vehicle/<int:id>', views.delete_vehicle, name='delete_vehicle'),

    path('plate_search', views.plate_search, name='plate_search'),
]

vehicle/models.py
from django.db import models
from driver.models import Driver

# Create your models here.

class Vehicle(models.Model):
    driver = models.ForeignKey(
        Driver,
        blank=True,
        null=True,
        default=None,
        on_delete=models.SET_DEFAULT,
    )
    model = models.CharField(max_length=50)
    vehicle_plate = models.CharField(max_length=7)
    checkin_datetime = models.DateTimeField(auto_now=True)
    parked = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.model} - {self.vehicle_plate}'

vehicle/views.py
from django.views.generic.edit import FormView
from vehicle.my_forms import VehicleRegisterForm, VehicleSearchForm
from vehicle.models import Vehicle
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib import messages

# Create your views here.

"""View that allows create instances of Vehicle and assign drivers"""
class VehicleRegisterFormView(FormView):
    template_name = 'vehicle_register_form.html'
    form_class = VehicleRegisterForm

def saving_vehicle(request):
    form = VehicleRegisterForm(request.POST)
    
    if form.is_valid():
        try:
            vehicle = get_list_or_404(Vehicle, vehicle_plate=form.cleaned_data['vehicle_plate'])
            if len(vehicle) >= 1:
                return render(request, 'vehicle_register_form.html', {'error': 'Automóvel já cadastrado!'})
        except:
            Vehicle.objects.create(
                model=form.cleaned_data['model'],
                vehicle_plate=form.cleaned_data['vehicle_plate'],
            )
            
            return redirect('vehicle:registered_vehicle')

"""Here we see all registered vehicles"""
def registered_vehicle(request):
    form = VehicleSearchForm()
    all_registered_vehicles = Vehicle.objects.all()

    return render(request, 'registered_vehicles.html', {
        'form': form,
        'all_registered_vehicles': all_registered_vehicles,
    })

"""View that allows delete a vehicle by plate"""
def delete_vehicle(request, id):
    vehicle = get_object_or_404(Vehicle, id=id)
    vehicle.delete()
    
    return redirect('vehicle:registered_vehicle')

"""View that displays only vehicle that match the search by plate"""
def plate_search(request):
    form = VehicleSearchForm(request.POST)

    if form.is_valid():
        vehicle = get_object_or_404(Vehicle, vehicle_plate=form.cleaned_data['plate_search'])

        return render(request, 'plate_search.html', {'vehicle': vehicle})

vehicle/templates/plate_search.html
{% extends "core_index.html" %}

{% block title %} | Busca de automóvel{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "plate_search.css" %}">
{% endblock css %}

{% block content %}
    <h2>Resultado da busca - Automóveis</h2>
    <section id="first_sec">
        <div id="plate_search">
            <span><b>Modelo:</b> {{ vehicle.model }}</span><br>
            <span><b>Placa:</b> {{ vehicle.vehicle_plate }}</span><br>
            <br>
        </div>        
    </section>
{% endblock content %}

vehicle/templates/registered_vehicles.html
{% extends "core_index.html" %}

{% block title %} | Automóveis cadastrados{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "registered_vehicles.css" %}">
{% endblock css %}

{% block content %}
    <section id="first_sec">
        <h2>Automóveis cadastrados</h2>
        <form id="search_form" action="{% url "vehicle:plate_search" %}" method="post">
            {% csrf_token %}
            <b>Placa do veículo:</b> {{ form.plate_search }}
            <input type="submit" value="Buscar">
            <br>
            <br>
        </form>
    </section>
    <section id="second_sec">
        {% for vehicle in all_registered_vehicles %}
            <div id="registered_vehicles">
                <span><b>Modelo:</b> {{ vehicle.model }}</span><br>
                <span><b>Placa:</b> {{ vehicle.vehicle_plate }}</span><br>
                <form id="delete_form" action="{% url "vehicle:delete_vehicle" vehicle.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Deletar">
                </form>
            </div>
        {% endfor %}
    </section>
{% endblock content %}

vehicle/templates/vehicle_register_form.html
{% extends "core_index.html" %}

{% block title %} | Cadastrar automóvel{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "vehicle_register_form.css" %}">
{% endblock css %}

{% block content %}
    {% if error %}
        {{ error }}
    {% else %}
        <h2>Cadastrar automóvel</h2>
        <form action="{% url "vehicle:saving_vehicle" %}" method="post">
            {% csrf_token %}
            <table>
                <tbody>
                    <tr>
                        <td>
                            Modelo
                        </td>
                        <td>
                            {{ form.model }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Placa
                        </td>
                        <td>
                            {{ form.vehicle_plate }}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="Enviar">
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    {% endif %}
{% endblock content %}