base_dir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('driver/', include('driver.urls')),
    path('vehicle/', include('vehicle.urls')),
    path('parking_space/', include('parking_space.urls')),
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
    path('', include('core.urls')),    
    path('admin_panel/', admin.site.urls),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('pre_finish/<int:parking_space_id>', views.pre_finish, name='pre_finish'),
    path('finish/<int:parking_space_id>/<int:vehicle_id>', views.finish, name='finish'),
    path('', views.index, name='index'),
]

parking_space/urls.py
from django.urls import path
from parking_space import views

app_name = 'parking_space'

urlpatterns = [
    path('parking_creation_form', views.ParkingSpaceCreationFormView.as_view(), name='parking_creation_form'),

    path('parking_space_history/<int:parking_space_id>', views.parking_space_history, name='parking_space_history'),

    path('parking_space_history/plate_search', views.parking_space_history_plate_search, name='parking_space_history_plate_search'),

    path('parking_assignment_form', views.ParkingAssignmentFormView.as_view(), name='parking_assignment_form'),

    path('saving_parking_place', views.saving_parking_place, name='saving_parking_place'),
    
    path('occupied_parking_spaces', views.occupied_parking_spaces, name='occupied_parking_spaces'),
]

parking_space/models.py
from django.db import models
from vehicle.models import Vehicle
from datetime import datetime, timezone, timedelta

# Create your models here.

"""Model representing parking spaces"""
class ParkingSpace(models.Model):
    occupied = models.BooleanField(default=False)
    occupied_by = models.OneToOneField(
        Vehicle,
        null=True,
        default=None,
        on_delete=models.SET_NULL       
    )
    def create_list():
        return list({})

    history = models.JSONField(default=create_list, null=True)

    def __str__(self):
        if self.id < 10:
            return f'Vaga 00{self.id}'
        elif self.id < 100:
            return f'Vaga 0{self.id}'
        return f'Vaga {self.id}'
        
    
    """Function to remove a veichle in a parking space"""
    def remove_auto(self):
        self.occupied = False
        self.occupied_by = None
    
    """Function to create the history of the parking space"""
    def add_history(self):
        current_datetime = datetime.now(timezone(timedelta(hours=-3)))
        occupied_by = self.occupied_by
        driver = self.occupied_by.driver
        vehicle_plate = self.occupied_by.vehicle_plate
        checkin_datetime = self.occupied_by.checkin_datetime - timedelta(hours=3) # -3 because Brazilian time is 3 hours behind UTC
        total_time = current_datetime - self.occupied_by.checkin_datetime

        self.history.append({
            'model': str(occupied_by),
            'driver': str(driver),
            'vehicle_plate': str(vehicle_plate),
            'checkin_datetime': str(checkin_datetime.strftime('%d/%m/%Y - %H:%M:%S')),
            'checkout_datetime': str(current_datetime.strftime('%d/%m/%Y - %H:%M:%S')),
            'total_time': str(total_time),
        })

parking_space/views.py
from django.views.generic.edit import FormView
from vehicle.my_forms import VehicleSearchForm
from parking_space.my_forms import ParkingSpaceCreationForm, ParkingAssignmentForm
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from parking_space.models import ParkingSpace
from vehicle.models import Vehicle

# Create your views here.

"""View that allows you to add new parking spaces"""
class ParkingSpaceCreationFormView(FormView):
    template_name = 'parking_creation_form.html'
    form_class = ParkingSpaceCreationForm

"""View that allows you to view the occupancy history of a parking space"""
def parking_space_history(request, parking_space_id):
    form = VehicleSearchForm()
    parking_space = get_object_or_404(ParkingSpace, id=parking_space_id)

    return render(request, 'parking_space_history.html', {'parking_space': parking_space, 'form': form})

"""View that displays only vehicle that match the search by plate, in parking space history"""
def parking_space_history_plate_search(request):
    form = VehicleSearchForm(request.POST)

    if form.is_valid():
        vehicle = get_object_or_404(Vehicle, vehicle_plate=form.cleaned_data['plate_search'])
        plate = vehicle.vehicle_plate
        parking_places = ParkingSpace.objects.all()
        search_result = list()
        for parking_place in parking_places:
            for vehicle in parking_place.history:
                if vehicle['vehicle_plate'] == plate:
                    search_result.append(vehicle)
                    vehicle['parking_place'] = parking_place

        return render(request, 'parking_space_history_plate_search.html', {'search_result': search_result})

"""View that allows assign autos to parking spaces"""
class ParkingAssignmentFormView(FormView):
    template_name = 'parking_assignment_form.html'
    form_class = ParkingAssignmentForm

def saving_parking_place(request):
    form = ParkingAssignmentForm(request.POST)

    if form.is_valid():
        parking_space = get_object_or_404(ParkingSpace, id=form.cleaned_data['parking_places'].id)
        parking_space.occupied = True
        parking_space.occupied_by = form.cleaned_data['occupied_by']
        parking_space.save()
        
        vehicle = get_object_or_404(Vehicle, vehicle_plate=form.cleaned_data['occupied_by'].vehicle_plate)
        vehicle.parked = True
        vehicle.driver = form.cleaned_data['driver']
        vehicle.save()
    
    return redirect('core:index')

"""Here we see all the occupied parking spaces"""
def occupied_parking_spaces(request):
    occupied_parking_spaces = ParkingSpace.objects.filter(occupied=True)

    return render(request, 'occupied_parking_spaces.html', {'occupied_parking_spaces': occupied_parking_spaces})

parking_space/templates/occupied_parking_spaces.html
{% extends "core_index.html" %}

{% block title %} | Vagas ocupadas{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "occupied_parking_spaces.css" %}">
{% endblock css %}

{% block content %}
    <h2>Vagas ocupadas</h2>
    <section id="first_sec">
        {% for parking in occupied_parking_spaces %}
            <div id="parking_spaces">
                <span><b>Vaga:</b> {{ parking.id }}</span><br>
                <span><b>Veículo:</b> {{ parking.occupied_by }}</span><br>
                <span><b>Horário de entrada:</b> {{ parking.occupied_by.checkin_datetime }}</span><br>
                <a id="finish" href="{% url "core:pre_finish" parking.id %}">Finalizar</a><br>
                <br>
            </div>
        {% endfor %}
    </section>
{% endblock content %}

parking_space/templates/parking_assignment_form.html
{% extends "core_index.html" %}

{% block title %} | Cadastrar entrada{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "parking_assignment_form.css" %}">
{% endblock css %}

{% block content %}
    <h2>Cadastrar entrada</h2>
    <form action="{% url "parking_space:saving_parking_place" %}" method="post">
        {% csrf_token %}
        <table>
            <tbody>
                <tr>
                    <td>
                        Vaga
                    </td>
                    <td>
                        {{ form.parking_places }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Ocupada
                    </td>
                    <td>
                        {{ form.occupied }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Veículo
                    </td>
                    <td>
                        {{ form.occupied_by }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Motorista
                    </td>
                    <td>
                        {{ form.driver }}
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="submit" value="Cadastrar">
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
{% endblock content %}

parking_space/templates/parking_creation_form.html
{% extends "core_index.html" %}

{% block title %} | Criar vagas{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "parking_creation_form.css" %}">
{% endblock css %}

{% block content %}
    <h2>Criar vagas</h2>
    <form action="{% url "core:index" %}" method="post">
        {% csrf_token %}
        <table>
            <tbody>
                <tr>
                    <td>
                        Quantidade
                    </td>
                    <td>
                        {{ form.qtd }}
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="submit" value="Enviar">
                    </td>
                </tr>
            </tbody>
        </table>        
    </form>
{% endblock content %}

parking_space/templates/parking_space_history.html
{% extends "core_index.html" %}

{% block title %} | Histórico de ocupação - {{ parking_space }}{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "parking_space_history.css" %}">
{% endblock css %}

{% block content %}
    <h2>Histórico de ocupação - {{ parking_space }}</h2>
    <section id="first_sec">
        {% for vehicle in parking_space.history %}
            <div id="parking_history">
                <b>Automóvel:</b> {{ vehicle.model }}<br>
                <b>Motorista:</b> {{ vehicle.driver }}<br>
                <b>Entrada:</b> {{ vehicle.checkin_datetime }}<br>
                <b>Saída:</b> {{ vehicle.checkout_datetime }}<br>
                <b>Tempo total:</b> {{ vehicle.total_time }}<br>
                <br>
            </div>            
        {% endfor %}
    </section>
{% endblock content %}

parking_space/templates/parking_space_history_plate_search.html
{% extends "core_index.html" %}

{% block title %} | Histórico do automóvel{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "parking_space_history_plate_search.css" %}">
{% endblock css %}

{% block content %}
    <h2>Resultado da busca - Automóveis</h2>
    <section id="first_sec">
            {% for vehicle in search_result %}
                <div id="plate_search">
                    <span><b>Vaga:</b> {{ vehicle.parking_place }}</span><br>
                    <span><b>Automóvel:</b> {{ vehicle.model }}</span><br>
                    <span><b>Motorista:</b> {{ vehicle.driver }}</span><br>
                    <span><b>Entrada:</b> {{ vehicle.checkin_datetime }}</span><br>
                    <span><b>Saída:</b> {{ vehicle.checkout_datetime }}</span><br>
                    <span><b>Tempo total:</b> {{ vehicle.total_time }}</span><br>
                    <br>
                </div>
            {% endfor %}  
    </section>
{% endblock content %}