base_dir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('driver/', include('driver.urls')),
    path('vehicle/', include('vehicle.urls')),
    path('parking_space/', include('parking_space.urls')),
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
    path('', include('core.urls')),    
    path('admin_panel/', admin.site.urls),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('pre_finish/<int:parking_space_id>', views.pre_finish, name='pre_finish'),
    path('finish/<int:parking_space_id>/<int:vehicle_id>', views.finish, name='finish'),
    path('', views.index, name='index'),
]

driver/urls.py
from django.urls import path
from driver import views

app_name = 'driver'

urlpatterns = [
    path('register_form', views.DriverRegisterFormView.as_view(), name='driver_register_form'),

    path('saving_driver', views.saving_driver, name='saving_driver'),

    path('registered', views.registered_drivers, name='registered_drivers'),

    path('delete/<str:cpf>', views.delete_drivers, name='delete_drivers'),

    path('search', views.driver_search, name='driver_search'),
]

driver/models.py
from django.db import models

# Create your models here.

class Driver(models.Model):
    driver_name = models.CharField(max_length=50)
    monthly = models.BooleanField(default=False)
    cnh = models.CharField(max_length=11)
    cpf = models.CharField(max_length=11)
    file_upload = models.FileField(upload_to='driver_docs/', blank=True)

    def __str__(self):
        return f'{self.driver_name} - CPF: {self.cpf}'

driver/views.py
from django.views.generic.edit import FormView
from driver.my_forms import DriverRegisterForm, DriverSearchForm
from driver.models import Driver
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from base_dir.functions import cpf_validator
from django.db import models
# Create your views here.

"""View that allows create instances of Driver"""
class DriverRegisterFormView(FormView):
    template_name = 'driver_register_form.html'
    form_class = DriverRegisterForm

def saving_driver(request): 
    if request.method == 'POST':
        form = DriverRegisterForm(request.POST, request.FILES)
        
        if 'file_upload' in request.FILES:
            file = request.FILES['file_upload']
        else:
            file = None
        
        if form.is_valid():
            drivers = Driver.objects.filter(Q(cpf=form.cleaned_data['cpf']) | Q(cnh=form.cleaned_data['cnh']))
            
            if len(drivers) >= 1:
                return render(request, 'driver_register_form.html', {'register_error': 'Motorista já cadastrado!'})

            cpf_validation = cpf_validator(form.cleaned_data['cpf'])

            if cpf_validation:
                driver = Driver.objects.create(
                    driver_name=form.cleaned_data['driver_name'],
                    monthly=form.cleaned_data['monthly'],
                    cnh=form.cleaned_data['cnh'],
                    cpf=form.cleaned_data['cpf'],
                    file_upload=file,
                )
                driver.save()
        
                return redirect('driver:registered_drivers')
            
            return render(request, 'driver_register_form.html', {
                'form': form,
                'cpf_error': 'CPF inválido!'
            })
    else:
        form = DriverRegisterForm()
        return render(request, 'driver_register_form.html', {'form': form})

"""Here we see all registered drivers"""
def registered_drivers(request):
    form = DriverSearchForm()
    all_registered_drivers = Driver.objects.all()

    return render(request, 'registered_drivers.html', {
        'form': form,
        'all_registered_drivers': all_registered_drivers,
    })

"""View that allows delete a driver by cpf"""
def delete_drivers(request, cpf):
    driver = get_object_or_404(Driver, cpf=cpf)
    driver.delete()
    return redirect('driver:registered_drivers')

"""View that displays only drivers that match the search by name"""
def driver_search(request):
    form = DriverSearchForm(request.POST)

    if form.is_valid():
        drivers = Driver.objects.filter(driver_name__contains=form.cleaned_data['name_search'])

        return render(request, 'driver_search.html', {'drivers': drivers})

driver/templates/driver_register_form.html
{% extends "core_index.html" %}

{% block title %} | Cadastrar motorista{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "driver_register_form.css" %}">
{% endblock css %}

{% block content %}
    <h2>Cadastrar motorista</h2>
    {% if register_error %}
        {{ register_error }}
    {% elif cpf_error %}
        {{ cpf_error }}
        <form action="{% url "driver:saving_driver" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tbody>
                    <tr>
                        <td>
                            Nome
                        </td>
                        <td>
                            {{ form.driver_name }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Mensalista
                        </td>
                        <td>
                            {{ form.monthly }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            CNH
                        </td>
                        <td>
                            {{ form.cnh }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            CPF
                        </td>
                        <td>
                            {{ form.cpf }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Documento
                        </td>
                        <td>
                            {{ form.file_upload }}
                        </td>
                    </tr>
                    <tr colspan="2">
                        <td>
                            <input type="submit" value="Enviar">
                        </td>                        
                    </tr>                    
                </tbody>
            </table>
        </form>
    {% else %}
        <form action="{% url "driver:saving_driver" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tbody>
                    <tr>
                        <td>
                            Nome
                        </td>
                        <td>
                            {{ form.driver_name }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Mensalista
                        </td>
                        <td>
                            {{ form.monthly }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            CNH
                        </td>
                        <td>
                            {{ form.cnh }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            CPF
                        </td>
                        <td>
                            {{ form.cpf }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Documento
                        </td>
                        <td>
                            {{ form.file_upload }}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="Enviar">
                        </td>
                    </tr>                    
                </tbody>
            </table>
        </form>                     
    {% endif %}
{% endblock content %}

driver/templates/driver_search.html
{% extends "core_index.html" %}

{% block title %} | Busca de motoristas{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "driver_search.css" %}">
{% endblock css %}

{% block content %}
    <h2>Resultado da busca - Motoristas</h2>
    <section id="first_sec">
        {% for driver in drivers %}
            <div id="driver_search">
                <span><b>Nome:</b> {{ driver.driver_name }}</span><br>
                <span><b>Mensalista:</b> {{ driver.monthly }}</span><br>
                <span><b>CNH:</b> {{ driver.cnh }}</span><br>
                <span><b>CPF:</b> {{ driver.cpf }}</span><br>
                <br>
            </div>
        {% endfor %}
    </section>
{% endblock content %}

driver/templates/registered_drivers.html
{% extends "core_index.html" %}

{% block title %} | Motoristas cadastrados{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "registered_drivers.css" %}">
{% endblock css %}

{% block content %}
    <section id="first_sec">
        <h2>Motoristas cadastrados</h2>
        <form id="search_form" action="{% url "driver:driver_search" %}" method="post">
            {% csrf_token %}
            <b>Nome do motorista:</b> {{ form.name_search }}
            <input type="submit" value="Buscar">
            <br>
            <br>
        </form>
    </section>
    <section id="second_sec">
        {% for driver in all_registered_drivers %}
            <div id="registered_drivers">
                <span><b>Nome:</b> {{ driver.driver_name }}</span><br>
                <span><b>Mensalista:</b> {{ driver.monthly }}</span><br>
                <span><b>CNH:</b> {{ driver.cnh }}</span><br>
                <span><b>CPF:</b> {{ driver.cpf }}</span><br>
                {% if driver.file_upload %}
                    <span><a id="doc" href="{{ driver.file_upload.url }}" target="_blank"><b>Documento</b></a></span><br>
                {% endif %}
                <form id="delete_form" action="{% url "driver:delete_drivers" driver.cpf %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Deletar">
                </form>
                <br>
                <br>
            </div>
        {% endfor %}
    </section>
{% endblock content %}