base_dir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('driver/', include('driver.urls')),
    path('vehicle/', include('vehicle.urls')),
    path('parking_space/', include('parking_space.urls')),
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
    path('', include('core.urls')),    
    path('admin_panel/', admin.site.urls),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('pre_finish/<int:parking_space_id>', views.pre_finish, name='pre_finish'),
    path('finish/<int:parking_space_id>/<int:vehicle_id>', views.finish, name='finish'),
    path('', views.index, name='index'),
]

driver/urls.py
from django.urls import path
from driver import views

app_name = 'driver'

urlpatterns = [
    path('register_form', views.DriverRegisterFormView.as_view(), name='driver_register_form'),

    path('saving_driver', views.saving_driver, name='saving_driver'),

    path('registered', views.registered_drivers, name='registered_drivers'),

    path('delete/<str:cpf>', views.delete_drivers, name='delete_drivers'),

    path('search', views.driver_search, name='driver_search'),
]

parking_space/urls.py
from django.urls import path
from parking_space import views

app_name = 'parking_space'

urlpatterns = [
    path('parking_creation_form', views.ParkingSpaceCreationFormView.as_view(), name='parking_creation_form'),

    path('parking_space_history/<int:parking_space_id>', views.parking_space_history, name='parking_space_history'),

    path('parking_space_history/plate_search', views.parking_space_history_plate_search, name='parking_space_history_plate_search'),

    path('parking_assignment_form', views.ParkingAssignmentFormView.as_view(), name='parking_assignment_form'),

    path('saving_parking_place', views.saving_parking_place, name='saving_parking_place'),
    
    path('occupied_parking_spaces', views.occupied_parking_spaces, name='occupied_parking_spaces'),
]

user_auth/urls.py
from django.urls import path
from user_auth import views

app_name = 'user_auth'

urlpatterns = [
    path('login_user', views.login_user, name='login_user'),

    path('logout_user', views.logout_user, name='logout_user'),

    path('register_user', views.register_user, name='register_user'),
]

vehicle/urls.py
from django.urls import path
from vehicle import views

app_name = 'vehicle'

urlpatterns = [
    path('vehicle_register_form', views.VehicleRegisterFormView.as_view(), name='vehicle_register_form'),

    path('saving_vehicle', views.saving_vehicle, name='saving_vehicle'),

    path('registered_vehicle', views.registered_vehicle, name='registered_vehicle'),

    path('delete_vehicle/<int:id>', views.delete_vehicle, name='delete_vehicle'),

    path('plate_search', views.plate_search, name='plate_search'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from parking_space.my_forms import ParkingSpaceCreationForm
from parking_space.models import ParkingSpace
from vehicle.my_forms import VehicleSearchForm
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime, timezone
from base_dir.functions import price_calculator
from vehicle.models import Vehicle
from django.contrib import messages

# Create your views here.

"""Main page"""
def index(request):
    form = ParkingSpaceCreationForm(request.POST)

    if form.is_valid():
        for _ in range(form.cleaned_data['qtd']):
            ParkingSpace.objects.create()
    
    parking_spaces = ParkingSpace.objects.filter(occupied=False)

    plate_search = VehicleSearchForm()

    return render(request, 'core_index.html', {'parking_spaces': parking_spaces, 'form': plate_search})

"""In this view, we calculate the amount to be paid and see all relevant information before receiving payment and releasing the parking space"""
def pre_finish(request, parking_space_id):
    parking_space = get_object_or_404(ParkingSpace, id=parking_space_id)
    
    checkin_datetime = parking_space.occupied_by.checkin_datetime
    current_datetime = datetime.now(timezone.utc)

    time_delta = current_datetime - checkin_datetime

    price = round(price_calculator(time_delta), 2)

    fmt_price = f'{price:.2f}'.replace('.', ',')

    if bool(parking_space.occupied_by.driver.monthly) == False:
        return render(request, 'core_pre_finish.html', {
            'monthly': False,
            'parking_space': parking_space,
            'checkin_datetime': checkin_datetime,
            'current_datetime': current_datetime,
            'price': fmt_price,
        })
    
    return render(request, 'core_pre_finish.html', {
            'monthly': True,
            'parking_space': parking_space,
            'checkin_datetime': checkin_datetime,
            'current_datetime': current_datetime,
        })

def finish(request, parking_space_id, vehicle_id):
    parking_space = get_object_or_404(ParkingSpace, id=parking_space_id)
    vehicle = get_object_or_404(Vehicle, id=vehicle_id)

    parking_space.add_history()
    parking_space.remove_auto()
    vehicle.parked = False
    vehicle.driver = None
    vehicle.save()
    parking_space.save()

    messages.success(request, "Saída registrada com sucesso!")

    return redirect('core:index')

core/templates/core_index.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estacionamento{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "header_nav.css" %}">
    {% block css %}
        <link rel="stylesheet" href="{% static "core_index.css" %}">
    {% endblock css %}
</head>
<body>
    <header>
        <h1>Estacionamento do Bosque</h1>
        {% if user.is_authenticated %}
            <h3><a id="login_link" href="{% url "user_auth:logout_user" %}">Logout</a></h3>
        {% else %}
            <h3><a id="logout_link" href="{% url "user_auth:login_user" %}">Login</a></h3>
        {% endif %}
        {% comment %} In other cases, this should also be placed in the else. But since I want to allow new users to be created only if someone is logged in, since this is a parking control system (only employees should be able to register other users) {% endcomment %}
        <h3><a id="register_link" href="{% url "user_auth:register_user" %}">Registrar usuário</a></h3>
    </header>    
    <nav>
        {% if user.is_authenticated %}
            <a class="nav_link" href="{% url "driver:driver_register_form" %}">Cadastro de motoristas</a>
        {% endif %}
        <a class="nav_link" href="{% url "driver:registered_drivers" %}">Motoristas cadastrados</a>
        {% if user.is_authenticated %}
            <a class="nav_link" href="{% url "vehicle:vehicle_register_form" %}">Cadastro de automóveis</a>
        {% endif %}
        <a class="nav_link" href="{% url "vehicle:registered_vehicle" %}">Automóveis cadastrados</a>
        <a class="nav_link" href="{% url "core:index" %}">Vagas disponíveis</a>
        <a class="nav_link" href="{% url "parking_space:occupied_parking_spaces" %}">Vagas ocupadas</a>
        {% if user.is_authenticated %}
            <a class="nav_link" href="{% url "parking_space:parking_assignment_form" %}">Cadastrar entrada</a>
            <a class="nav_link" href="{% url "parking_space:parking_creation_form" %}">Criar vagas</a>
        {% endif %}
    </nav>
    <main>
        {% block content %}
            <section id="first_sec">
                {% if messages %}
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                {% endif %}
                <h2 class="sec_title">Vagas disponíveis</h2>
                <div id="unoccupied_parking">
                    {% for parking_space in parking_spaces %}
                        <a class="parking_link" href="{% url "parking_space:parking_space_history" parking_space.id %}">{{ parking_space }}</a>
                    {% endfor %}
                </div>            
            </section>
            <section id="second_sec">
                <h2 class="sec_title">Buscar automóvel</h2>
                <div id="form">
                    <form action="{% url "parking_space:parking_space_history_plate_search" %}" method="post">
                        {% csrf_token %}
                        <b>Placa do veículo:</b> {{ form.plate_search }}
                        <input id="button" type="submit" value="Buscar">
                    </form>
                </div>
            </section>            
        {% endblock content %}
    </main> 
</body>
</html>

core/templates/core_pre_finish.html
{% extends "core_index.html" %}

{% block title %} | Resumo{% endblock title %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "core_pre_finish.css" %}">
{% endblock css %}

{% block content %}
    <h2>Resumo</h2>
    <section id="first_sec">
        <div id="parking_spaces">        
            {% if monthly %}
                <span><b>Vaga:</b> {{ parking_space }}</span><br>
                <span><b>Horário de entrada:</b> {{ checkin_datetime }}</span><br>
                <span><b>Horário de saída:</b> {{ current_datetime }}</span><br>
                <span>{{ time_delta }}</span><br>
                <br>
            {% else %}
                <span><b>Vaga:</b> {{ parking_space }}</span><br>
                <span><b>Horário de entrada:</b> {{ checkin_datetime }}</span><br>
                <span><b>Horário de saída:</b> {{ current_datetime }}</span><br>
                <span>{{ time_delta }}</span><br>
                <span><b>Total:</b> R$ {{ price }}</span><br>
                <br>
            {% endif %}
            <form action="{% url "core:finish" parking_space.id parking_space.occupied_by.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Confirmar pagamento">
            </form>
        </div>
    </section>    
{% endblock content %}